// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      // 🚫 غير مدعومة حالياً
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError('This platform is not configured for Firebase.');

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBymhgzft9XEIByyFFgkhSEypjsoaZPS8w',
    appId: '1:517530251448:web:ccb10d0414c6433b60c44d',
    messagingSenderId: '517530251448',
    projectId: 'lets-play-app-prod',
    authDomain: 'lets-play-app-prod.firebaseapp.com',
    storageBucket: 'lets-play-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrn-EtM2LAVFNIz49PY_k6kiOiVigK7k',
    appId: '1:517530251448:android:5505921fde43ccce60c44d',
    messagingSenderId: '517530251448',
    projectId: 'lets-play-app-prod',
    storageBucket: 'lets-play-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH0kzL5rU3Xu8hdGELdNsm7sT774efY-w',
    appId: '1:517530251448:ios:40b8525dc562ab8160c44d',
    messagingSenderId: '517530251448',
    projectId: 'lets-play-app-prod',
    storageBucket: 'lets-play-app-prod.firebasestorage.app',
    iosBundleId: 'com.example.letsPlayapp',
  );
}
